Vagrant.configure(2) do |config|
  # box search page --> https://atlas.hashicorp.com/boxes/search
  config.vm.box = "bento/centos-7.1"
  config.vbguest.auto_update = false

  config.vm.provider "virtualbox" do |vb|
    ### vagrant hostname 
    vb.name = "centos7"
    vb.customize ['modifyvm', :id,
                  "--memory", 1024]
  end  

  config.vm.define :web1 do |web|
    ### vbox name
    web.vm.hostname = 'centos7'
    ### determined specific IP.
    web.vm.network "private_network", ip: "192.168.33.12"
  end
 
  ### settitng of synced_folder
  config.vm.synced_folder "../../", "/develop/base-centos", \
    :create => true, \
    :owner  => 'root', \
    :group  => 'root', \
    :mount_options => ['dmode=755,fmode=755'] 
  # end



### install of chef recipe
  config.omnibus.chef_version=:latest
  config.vm.provision  "chef_zero" do |chef|
    chef.cookbooks_path = "./rhel7/cookbooks"
    chef.roles_path = "rhel7/roles"
    chef.add_role "common"
    # chef.add_role "elasticsearch"
  end

  config.vm.provision :shell, :path => "../inst-docker.sh"

end
