Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-6.7"
  config.vbguest.auto_update = false
  config.omnibus.chef_version=:latest


  config.vm.define :web1 do |web|
    ### determined specific IP.
    web.vm.network "private_network", ip: "192.168.33.12"
    ### vbox name
    web.vm.hostname = 'vagrant-svr'
  end

  config.vm.provider "virtualbox" do |vb|
    ### vagrant hostname 
    vb.name = "base-centos"
    vb.customize ['modifyvm', :id,
                  "--memory", 1024]
    #               "--size" , 2048]
    # vb.customize ['modifyvm', :id, "--memory", 1024]
    # vb.customize ['modifyvm', :id, "--memory", 1024]
  end  
 
  ### settitng of synced_folder
  config.vm.synced_folder "../", "/develop/base-centos", \
    :create => true, \
    :owner  => 'root', \
    :group  => 'root', \
    :mount_options => ['dmode=755,fmode=755'] 
  # end



  ### install of chef recipe
  config.vm.provision :chef_zero do |chef|
    chef.add_recipe "base"
  end

end
