# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|
  # config.vm.box = "chef/centos-6.6"
  config.vm.box = "bento/centos-6.7"
  config.vbguest.auto_update = false
  # config.omnibus.chef_version=:latest


  config.vm.provider "virtualbox" do |vb|
  ### vagrant hostname 
  vb.name = "base-centos"
  # vb.name = ""
  end  


  config.vm.define :web1 do |web|
  ### determined specific IP.
  web.vm.network "private_network", ip: "192.168.33.12"
  ### vbox name
  web.vm.hostname = 'vagrant-svr'
  end


  ###  ### install of chef recipe
  ###  config.vm.provision :chef_zero do |chef|
  ###    chef.add_recipe "base"
  ###  end
 
  ### settitng of synced_folder
  config.vm.synced_folder "../", "/develop/base-centos", \
    :create => true, \
    :owner  => 'root', \
    :group  => 'root', \
    :mount_options => ['dmode=755,fmode=755'] 
  # end

end



  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL
  # end
