Vagrant.configure(2) do |config|
  # config.vm.box = "bento/centos-6.7"
  config.vbguest.auto_update = false

  config.vm.define :svr01 do |server|
    ### determined specific IP.
    server.vm.network "private_network", ip: "192.168.33.11"
    ### vbox name
    server.vm.hostname = 'svr01'
    ### box setting
    server.vm.box = "bento/centos-6.7"
  end

  config.vm.define :svr02 do |server|
    ### determined specific IP.
    server.vm.network "private_network", ip: "192.168.33.12"
    ### vbox name
    server.vm.hostname = 'svr02'
    ### box setting
    server.vm.box = "bento/centos-6.7"
  end

  config.vm.define :svr03 do |server|
    ### determined specific IP.
    server.vm.network "private_network", ip: "192.168.33.13"
    ### vbox name
    server.vm.hostname = 'svr03'
    ### box setting
    server.vm.box = "bento/centos-6.7"
  end

  config.vm.provider "virtualbox" do |vb|
    ### vagrant hostname 
    # vb.name = "base-centos-step2"
    vb.customize ['modifyvm', :id,"--memory", 512]
    vb.customize ['modifyvm', :id,"--natdnshostresolver1", "on"]
    vb.customize ['modifyvm', :id,"--natdnsproxy1", "on"]
  end  
 
  ### settitng of synced_folder
  config.vm.synced_folder "../../", "/develop/base-centos", \
    :create => true, \
    :owner  => 'root', \
    :group  => 'root', \
    :mount_options => ['dmode=755,fmode=755'] 


  ### install of chef recipe
    config.omnibus.chef_version=:latest
    config.vm.provision  "chef_zero" do |chef|
      chef.cookbooks_path = ["./step2-repo/cookbooks", "./step2-repo/site-cookbooks"]
      chef.roles_path = "step2-repo/roles"
      chef.add_role "common"
      # chef.add_role "elasticsearch"
    end

end
